version: "3.9"

services:
  minio:
    container_name: min_io_data_storage
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - data_copy_paste:/data

volumes:
  data_copy_paste: